//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Test.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    /// <summary>
    /// TestWebApiEntities
    /// </summary>
    public partial class TestWebApiEntities : DbContext, ITestWebApiEntities
    {
        public TestWebApiEntities()
            : base("name=TestWebApiEntities")
        {
        }
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        /// <summary>
        /// Set de Usuarios
        /// </summary>
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
